---
- name: Creating Image
  hosts: localhost
  tasks:
   - name: Create Image
     command: docker build -t kedar1906/addressbook .
     args:
      chdir: /opt/address-book
   - name: Push Image
     command: docker push kedar1906/addressbook
  